Add lighthouse CI support into Github Action

diff --git a/.github/workflows/zeitdeploy.yml b/.github/workflows/zeitdeploy.yml
--- a/.github/workflows/zeitdeploy.yml
+++ b/.github/workflows/zeitdeploy.yml
@@ -13,7 +13,13 @@ jobs:
       - uses: actions/setup-node@v1
         with:
           node-version: 10
-      - run: npm install
-      - run: npx now --prod --token $ZEIT_TOKEN
+      - name: Deploy to zeit
+        run: |
+          npm install
+          npx now --prod --token $ZEIT_TOKEN
         env:
           ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}
+      - name: Run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
